### PR TITLE
Fix assert when initializing with no joysticks on OS X

### PR DESCRIPTION
**Pull request by postcasio**
On OS X, Allegro asserts when the joystick index is out of range.
This also changes some joystick functions so that they will correctly
throw on an out of range parameter.

### CODE REVIEW

**Comment by postcasio** [comment]
Good point - if Sphere just returns falsy values for nonexistant joysticks, then the current range error in Bind/Unbind should be replaced with a return 0, right? And the same check should be added to the other functions that are currently missing it.

**Comment by fatcerberus** [comment]
That's pretty much it, yes.  That's why I test against MAX_JOYSTICKS instead of the actual number present.  Technically the joystick functions shouldn't throw at a range error at all for full compatibility (Sphere happily lets you ask for ridiculous things like joystick 812 button 413), but I can chalk that up to minisphere being more strict.  The point is, if the engine supports 4 joysticks and a game asks for the state of joystick 0 while no device is actually present, that shouldn't be an error.  Returning a zero is sufficient.

**Comment by fatcerberus** [comment]
Followup: I should note, however, that BindJoystickButton should still bind the button in case a joystick is connected later.  It's not implemented now, but I want to implement hotplugging for joysticks in v1.1.

**Comment by fatcerberus** [comment]
Merged, but not before fixing Bind/Unbind to be Sphere-compatible again.  Thanks for catching the assert, I guess this is what I get for not using the debug library for Allegro in my debug builds...

**Comment by fatcerberus** [comment]
So I was looking at Allegro's source and using the debug library wouldn't have helped me discover this: For whatever reason the Windows implementation doesn't include an assert for out-of-range values (it only asserts if index < 0). Yay for consistency!  Although I'm wondering if the assert is incorrect, since al_get_joystick() is explicitly specified in the documentation to just return NULL if the joystick doesn't exist.

**Comment by postcasio** [comment]
> Although I'm wondering if the assert is incorrect, since al_get_joystick() is explicitly specified in the documentation to just return NULL if the joystick doesn't exist.

I had a look and this isn't strictly true...

> The number may be from 0 to al_get_num_joysticks-1. If successful a pointer to a joystick object is returned, which represents a physical device. Otherwise NULL is returned.

It returns NULL if there is an error getting the joystick, not if the joystick number is out of range. Out of range numbers shouldn't be used.

**Pull request merged**
