### PR TITLE
Add Shader#setSampler(name, texture, texture_unit)

### PR DESCRIPTION
**Pull request by postcasio**

### CODE REVIEW

**Comment by fatcerberus** [comment]
This is tricky API-wise. While I like the API you have here, it's nice and simple and easy to understand, texture *units* themselves are technically a separate piece of GPU state than the unit *index* used to set the sampler uniform. I don't know if texture units are indexed by anything else in practice, though. If they are, it might make sense to have a separate API to populate texture units, and then `.setSampler()` would just take a texture unit index.

**Comment by postcasio** [comment]
Yeah the API is just wrapping the Allegro API, like the other Sampler methods. I don't believe anything else cares about them, the usual usage is to bind and set the uniform for each draw. There's no Allegro API to bind separately, anyway.

One other thing that would be useful is a way to access the supported number of texture units which needs an OpenGL call, a little beyond my capability. With reasonably modern cards even cheap integrated chips have quite a few units though.

**Comment by fatcerberus** [comment]
The code changes seems pretty straightforward, no issues that I can see. The API will remain experimental for a while so there's still time to make changes if needed later. 😃  I'll merge this in.

**Comment by fatcerberus** [comment]
Okay so I'm not sure why it suddenly decided there was a merge conflict, but could you resolve that and then I'll get this in?

**Pull request closed without merging**
